---
title: "Chapter 2- mortality"
output: pdf_document
date: "2026-03-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Import posteriors from ecological model
```{r}
library(dplyr)
site.order.m1 <-c("JA", "CO" ,"BC" ,"CR", "CS", "JF" ,"MU", "NP", "PP", "PV", "SS" ,"VE")
site.order <- c("JA", "CO", "BC" ,"CS" ,"CR" ,"MU", "VE" ,"PV" ,"MI", "JC", "CA" ,"SJ", "CV", "SE", "JG" ,"NP" ,"PP" ,"SS" ,"JF")
#laptop
#r_prior_df_eco <- readRDS("~/Library/CloudStorage/OneDrive-VirginiaTech/Github/arapaima_phenom_mod/priors/r_arena_priors.rds")
#r_hyperpriors  <- readRDS("~/Library/CloudStorage/OneDrive-VirginiaTech/Github/arapaima_phenom_mod/priors/r_hyperpriors.rds")
#beta_priors    <- readRDS("~/Library/CloudStorage/OneDrive-VirginiaTech/Github/arapaima_phenom_mod/priors/beta_priors.rds")

#desktop
r_prior_df_eco <- readRDS("C:/Users/emmah6/OneDrive - Virginia Tech/Github/arapaima_phenom_mod/priors/r_arena_priors.rds")
r_hyperpriors  <- readRDS("C:/Users/emmah6/OneDrive - Virginia Tech/Github/arapaima_phenom_mod/priors/r_hyperpriors.rds")
beta_priors    <- readRDS("C:/Users/emmah6/OneDrive - Virginia Tech/Github/arapaima_phenom_mod/priors/beta_priors.rds")
# Build full 19-arena frame
r_prior_df <- data.frame(arena = site.order) %>%
left_join(r_prior_df_eco, by = "arena") %>%
mutate(
r_mean = ifelse(is.na(r_mean), r_hyperpriors$r_mean_est, r_mean),
r_sd   = ifelse(is.na(r_sd),   1.5, r_sd * 2)
)
r_prior_m2 <- data.frame(
  site   = site.order,
  r_mean = r_prior_df$r_mean[match(site.order, r_prior_df$arena)],
  r_sd   = r_prior_df$r_sd[match(site.order, r_prior_df$arena)]
)

# replace uninformative SDs (from arenas not in model 1) with hyperprior SD
uninformative <- r_prior_m2$r_sd > 0.2
r_prior_m2$r_mean[uninformative] <- r_hyperpriors$r_mean_est
r_prior_m2$r_sd[uninformative]   <- r_hyperpriors$r_mean_sd * 2


```
# Rule compliance
using perceptions data from Cae 
``` {r compliance}
data4Emmav07 <- read.csv("data4Emmav07.csv")
cae_data <- data4Emmav07[,64:67]
cae_data[is.na(cae_data)] <- 0
cae_means <- cae_data %>%
  group_by(idses) %>%
  summarise_all(mean, na.rm = TRUE) 

codes <- readxl::read_xlsx("code_matching.xlsx")
ses_code <- unique(codes[,4:5])

per_comp <- merge(ses_code, cae_means, by.x= "SES", by.y = "idses")
# which rule should we focus on? for now- making an index by summing across the 3
per_comp <- per_comp %>% mutate(comp_index = compmgts + compmgtsea + compmgtla) 
per_comp2 <- per_comp[match(site.order, per_comp$SES.name),]

noncompliance_scale <- as.vector(scale(per_comp2[,6]))
```
# Poaching 
poaching data- Take average of top 5 poached lakes for all ses arenas
```{r poaching}
library(dplyr)
poach_raw <- read.csv("poaching_emma_lake.csv")
# combine poaching days for each lake from high and low water season
# take average of the top 5 lakes to create poaching index
poach_index <- poach_raw %>%
  group_by(SES, lago) %>%
  summarise(lake_total = sum(days_poached, na.rm = TRUE), .groups = "drop") %>%
  group_by(SES) %>%
  slice_max(order_by = lake_total, n = 5) %>%
  summarise(top5_poach = sum(lake_total), .groups = "drop") %>%
  mutate(SES = factor(SES, levels = site.order)) %>%
  arrange(SES) %>%
  mutate(poach_scaled = scale(top5_poach)[,1])
```
# Indirect questioning
```{r indirect}
iq_estimates <- readRDS("C:/Users/emmah6/OneDrive - Virginia Tech/Github/arapaima_phenom_mod/priors/indirect_estimates.rds")
#combining size and season as an index (lake was not correlated)
iq_estimates_clean <- iq_estimates %>%
  filter(!(rule == "compmgtsea" & idses == 6))

iq_index_clean <- iq_estimates_clean %>%
  filter(rule %in% c("compmgts", "compmgtsea")) %>%
  group_by(idses) %>%
  summarise(incompliance_harvest = mean(mean, na.rm=TRUE), .groups="drop") %>%
  left_join(ses_code, by = c("idses" = "SES")) %>%
  mutate(SES.name = factor(SES.name, levels = site.order)) %>%
  arrange(SES.name) %>%
  mutate(incompliance_scaled = scale(incompliance_harvest)[,1])
```
# Ecological variables
```{r catch/count}
arenas <- 19 #all of them!
years <- 5 #2018-2022, just the last 5 (relative to the survey)
shared_model_years <- as.character(2006:2022)

#old_count <- read.csv("smoothedcounts_v1.csv")
#count <- count[,-1]
#colnames(count) <- c("SES", 1999:2023)
#count_best <- count[-c(4,7:8,10:11,16:17),]
SES_counts <- read.csv("C:/Users/emmah6/OneDrive - Virginia Tech/Github/arapaima_phenom_mod/smoothedcounts_4_2_26.csv", check.names = FALSE)
rownames(SES_counts) <- SES_counts[,1]

#updating with Pris' data
missing_mam <- read.csv("catch_count_year_SES.csv")
pris_ja <- missing_mam[, c(1, 6, 8)] %>%
  setNames(c("SES", "year", "adult_count")) %>%
  filter(SES == "JA") %>%
  arrange(year)
pris_ja_vec <- pris_ja$adult_count[match(shared_model_years,as.character(pris_ja$year))]
SES_counts["JA", shared_model_years] <- pris_ja_vec

model_years_m2 <- as.character(2018:2022)
C <- round(as.matrix(SES_counts[site.order, model_years_m2]))  # all 19 arenas
storage.mode(C) <- "numeric"

catch= read.csv("catch_count_year_SES_12_3.csv")
quota_catch <- catch[,c(1,4,7,8)]
quota_catch <- quota_catch[-184,]
c1 <- quota_catch[, c(1,2,4)]
colnames(c1) <- c("SES", "year", "report_catchtotal")
#missing_mam <- read.csv("catch_count_year_SES.csv")
mam_catch <- missing_mam[,c(1,6,9)]
c2<- rbind(c1, mam_catch)
c3<- dplyr::distinct(c2)
c3.5<- c3[-c(138,140),]
c4<- c3.5[order(c3.5$year, decreasing= FALSE),]
c5 <- tidyr::pivot_wider(c4, names_from = "year", values_from = "report_catchtotal")

E <- c5[match(site.order, c5$SES), ]
E <- E[, model_years_m2]  
E[is.na(E)] <- 0
E <- as.matrix(E)
storage.mode(E) <- "numeric"
rownames(E) <- site.order

w_input <- read.csv("C:/Users/emmah6/OneDrive - Virginia Tech/Github/arapaima_phenom_mod/w_productivity_weighted_19.csv", row.names = "SES", check.names = FALSE)
W <- as.matrix(w_input[site.order, model_years_m2])
storage.mode(W) <- "numeric"
```
```{r min water level}
library(dplyr)
min_wl_bySES <- read.csv("min_wl_ses.csv")
min_wl <- min_wl_bySES[1:19, -2]
colnames(min_wl) <- c("SES", 1995:2023)
min_wl <- min_wl[match(site.order, min_wl$SES), ]

######
Codigo  <- c("12351000", "13150003", "12872000")
Estacao <- c("FB", "CO", "MA")
stations <- data.frame(Codigo = Codigo, Estacao = Estacao)

# ANA station names as they appear in list_stations.xlsx, matched to Estacao codes
station_names <- data.frame(
  ANA.station = c("Fonte Boa", "Coari", "Maraa"),
  Estacao     = c("FB", "CO", "MA")
)

ses_lookup <- readxl::read_excel("list_stations.xlsx") %>%
  filter(!is.na(SES)) %>%
  left_join(station_names, by = "ANA.station") %>%
  select(SES, Estacao)

station_key <- data.frame(
  Estacao    = Estacao,
  station_id = seq_along(Estacao)
)

station_id <- min_wl %>%
  mutate(SES = site.order) %>%
  left_join(ses_lookup, by = "SES") %>%
  left_join(station_key, by= "Estacao") %>%
  pull(station_id)

Wl_min_raw <- as.matrix(
  min_wl[1:19, ] %>%
    left_join(ses_lookup, by = "SES") %>%
    distinct(Estacao, .keep_all = TRUE) %>%
    slice(match(station_key$Estacao, Estacao)) %>%
    select(as.character(2016:2020)))

rownames(Wl_min_raw) <- station_key$Estacao
Wl_min_scaled <- t(scale(t(Wl_min_raw)))
```
```{r flooded forest}
library(dplyr)
hess_habs <- readxl::read_xls("hess_4k_pixels.xls")
hess <- hess_habs %>% mutate(totalpix = (C_0+C_1+C_11+C_13+C_21+C_33+C_44+C_51+C_67+C_77+C_88+C_89+C_99+C_200+C_255),
                        p_floodforest= ((C_77+C_89+C_99)/totalpix))
hess_trim <- hess[2:20,c(2,23)]
colnames(hess_trim) <- c("SES", "p_ff")
hess_trim <- hess_trim %>% mutate(pct_ff = p_ff *100)
hess_tiny <- hess_trim[,c(1,3)]
colnames(hess_tiny) <- c("SES", "Percent area flooded forest")

hess_final <- na.omit(hess_tiny[match(site.order, hess_tiny$SES), ])


max_wl_bySES <- read.csv("max_wl_bySES.csv")
max_wl <- max_wl_bySES[1:19, c(1,25:29)]
colnames(max_wl) <- c( "SES", 2016:2020)
Wl_max_raw <- max_wl[match(site.order, max_wl$SES), ]

Wl_max_plus <- left_join(Wl_max_raw, hess_tiny, by = "SES")
# Step 3: multiply each year column by the percent area flooded forest
year_cols <- as.character(2016:2020)
Wl_flood <- Wl_max_plus
Wl_flood[, year_cols] <- Wl_max_plus[, year_cols] * 
                          (Wl_max_plus$`Percent area flooded forest` / 100)

ff_matrix <- as.matrix(Wl_flood[, year_cols])
rownames(ff_matrix) <- site.order

# global scaling to preserve between-arena variation
ff_mean   <- mean(ff_matrix, na.rm = TRUE)
ff_sd     <- sd(as.vector(ff_matrix), na.rm = TRUE)
ff_scaled <- (ff_matrix - ff_mean) / ff_sd
rownames(ff_scaled) <- site.order


```
# Model
```{r data bundle/initial sim}
# Detection parameters for initialization
p_obs_fixed  <- 0.85
#beta6_target <- 0.485
p_unrep_start <- 0.17
logit_start   <- log(p_unrep_start / (1 - p_unrep_start))

# Back-calculate N_implied for N_start
N_implied <- matrix(NA, nrow=arenas, ncol=years)
for(j in 1:arenas){
  for(t in 1:years){
    N_implied[j,t] <- ceiling(C[j,t] / (W[j,t] * p_obs_fixed))
  }
}

# Initialize N, M, U
N_sim <- matrix(NA, nrow=arenas, ncol=years)
M_sim <- matrix(NA, nrow=arenas, ncol=years)
U_sim <- matrix(NA, nrow=arenas, ncol=years-1)

for(j in 1:arenas){
  for(t in 1:years){
    w_sim      <- max(W[j,t], 0.01)
    M_sim[j,t] <- max(ceiling(C[j,t] / p_obs_fixed), C[j,t] + 5)
    N_sim[j,t] <- max(ceiling(M_sim[j,t] / w_sim), M_sim[j,t] + 10)
    if(E[j,t] > 0){
      N_sim[j,t] <- max(N_sim[j,t], E[j,t] * 2)
      M_sim[j,t] <- max(M_sim[j,t], ceiling(E[j,t] * 2 * w_sim))
    }
    if(M_sim[j,t] > N_sim[j,t]) N_sim[j,t] <- M_sim[j,t] + 10
    if(C[j,t]     > M_sim[j,t]){
      M_sim[j,t] <- C[j,t] + 5
      N_sim[j,t] <- max(N_sim[j,t], M_sim[j,t] + 10)
    }
  }
  for(t in 1:(years-1)){
    avail      <- max(N_sim[j,t] - E[j,t], 0)
    U_sim[j,t] <- min(round(avail * p_unrep_start), avail)
  }
}

storage.mode(N_sim) <- "numeric"
storage.mode(M_sim) <- "numeric"
storage.mode(U_sim) <- "numeric"

data.bundle_m <- list(
  C                = C,
  E                = E,
  w_fixed          = W,
  indirect         = iq_index_clean$incompliance_scaled,
  poaching         = poach_index$poach_scaled,
  Minw             = Wl_min_scaled,
  Ff               = ff_scaled,
  arenas           = arenas,
  years            = years,
  station_id       = station_id,
  N_start          = apply(N_implied, 1, max),
  r_prior_mean     = r_prior_m2$r_mean,
  r_prior_sd       = r_prior_m2$r_sd,
  beta1_prior      = beta_priors$beta1_mean,
  beta1_prior_sd   = beta_priors$beta1_sd * 2,
  beta3_prior      = beta_priors$beta3_mean,
  beta3_prior_sd   = beta_priors$beta3_sd * 2
)
```
3 tier model
```{r JAGS full}
library(rjags)
library(jagsUI)

modfile_mort <- tempfile()
writeLines("
model {
  #---------------------------------------------------
  # Priors
  #---------------------------------------------------
 # r_mean  ~ dnorm(r_mean_prior, 1/pow(r_mean_prior_sd, 2))T(-0.5, 0.5)
 # sigma_r ~ dnorm(sigma_r_prior, 1/pow(sigma_r_prior_sd, 2))T(0,)
 # tau_r   <- 1/pow(sigma_r, 2)

  beta1 ~ dnorm(beta1_prior, 1/pow(beta1_prior_sd, 2))
  beta3 ~ dnorm(beta3_prior, 1/pow(beta3_prior_sd, 2))

  mu_unrep    ~ dnorm(0, 1/pow(1.5, 2))
  sigma_unrep ~ dnorm(0, 1/pow(1, 2))T(0,)
  tau_unrep   <- 1/pow(sigma_unrep, 2)
  
 #priors on alpha and beta of distribution for p_unrep
 #shp1 ~ dgamma(0.01, 0.01)
 #shp2 ~ dgamma(0.01, 0.01)
 phi ~ dgamma(0.01, 0.01)
 beta8 ~ dnorm(0, 1/pow(1,2))T(0,)
 beta7 ~ dnorm(0, 1/pow(1,2))T(0,)
 
 
 intercept ~ dnorm(-1, 1/pow(1.5, 2))
#---------------------------------------------------
# Ecological Process model
#---------------------------------------------------
for (j in 1:arenas) {
      N[j,1] ~ dpois(N_start[j]) 
      r[j] ~ dnorm(r_prior_mean[j], 1/pow(r_prior_sd[j], 2))T(-0.5, 0.5)
     
     logit(mu_p_unrep[j]) <- intercept + beta8*indirect[j] + beta7*poaching[j] 
     shp1[j] <- phi*mu_p_unrep[j]
     shp2[j] <- phi*(1-mu_p_unrep[j])
     
     p_unrep[j] ~ dbeta(shp1[j], shp2[j])
     
    for (t in 1:(years-1)){
      
      U[j,t] ~ dbin(p_unrep[j], N[j,t]-E[j,t]) #confirm that harvest and count happen in the same year 
      #binomial(probability of unreported fishing, number of fish not already reported as catch)

      Ftot[j,t] <- E[j,t] + U[j,t] # legal + rule breaking and poaching 
      
      N_post_harvest[j,t] <- N[j,t] - Ftot[j,t]
      
      # Growth to next year
     growth_rate[j,t] <- r[j] + 
     (beta1 * Minw[station_id[j],t]) + 
     (beta3 * Ff[j,t]) 
      
      N_expected[j,t+1] <- N_post_harvest[j,t] * exp(growth_rate[j,t])
      N[j,t+1] ~ dpois(N_expected[j,t+1])
    }
}
  #---------------------------------------------------
  # Proportion of the population actually sampled
  #---------------------------------------------------
 for (j in 1:arenas){
    for (t in 1:years){
      
      M[j,t] ~ dbin(w_fixed[j,t], N[j,t])
    }
  }
  #---------------------------------------------------
  # Observation model for C (counts) - regular binomial 
  #---------------------------------------------------
    p_obs <- 0.85 #fixing to reduce model complexity 

for (j in 1:arenas) {
    for (t in 1:years){
      
      C[j,t] ~ dbin(p_obs , M[j,t])
    }
  }
  
  #---------------------------------------------------
  # Derived quantities
  #---------------------------------------------------
  for (j in 1:arenas) {
    for (t in 1:(years-1)) {
    lambda[j,t+1] <- N[j,t+1]/N[j,t]
    }
  }
}

", con = modfile_mort)

# Initialization function
inits_m <- function() {
  
  p_unrep_init <- rbeta(arenas, 2, 10)  # mean ~0.17, constrained away from 1
  
  list(
    N           = N_sim,
    M           = M_sim,
    U           = U_sim,
   # r_mean      = rnorm(1, r_hyperpriors$r_mean_est, 0.02),
   # sigma_r     = runif(1, 0.01, 0.05),
    r           = rnorm(arenas, r_hyperpriors$r_mean_est, 0.01),
    beta1       = rnorm(1, beta_priors$beta1_mean, 0.001),
    beta3       = rnorm(1, beta_priors$beta3_mean, 0.001),
    beta8       = runif(1,0,0.1),
    beta7       = runif(1,0,0.1),
    mu_unrep    = rnorm(1, logit_start, 0.1),
    sigma_unrep = runif(1, 0.05, 0.15),
    phi         = runif(1, 5, 15),
    intercept   = rnorm(1, -1, 0.1),
    p_unrep     = p_unrep_init
  )
}

# Parameters to monitor
parameters_m <- c("beta1", "beta3", "beta8", "beta7", "mu_unrep", 
                "sigma_unrep", "p_unrep", "lambda", "N", "U", "r", "phi", "intercept")

out_m <- jags(data = data.bundle_m,
            inits = inits_m,
            parameters.to.save = parameters_m,
            model.file = modfile_mort,
            n.chains = 3,
            n.adapt = 30000,
            n.iter = 200000,
            n.burnin = 100000,
            n.thin = 75,
            parallel = TRUE)

traceplot(out_m, parameters = parameters_m)
```
Diagnostics
```{r diagnostics, echo=FALSE}
#install.packages("jagshelper")
library(jagshelper)

key_params <- c("beta1", "beta3", "beta7", "beta8")

for (param in key_params) {
  if (param %in% rownames(out_m$summary)) {
    cat("\n", param, ":\n", sep="")
    param_summary <- out_m$summary[param, ]
    print(round(param_summary, 4))
  } else {
    cat("\n", param, ": NOT FOUND\n", sep="")
  }
}

check_neff(out_m, 200)

check_Rhat(out_m)

if ("mean" %in% names(out_m)) {
  cat("\nParameter means:\n")
  for (param in key_params) {
    if (param %in% names(out_m$mean)) {
      cat(sprintf("  %-12s = %8.4f\n", param, out_m$mean[[param]]))
    }
  }
}

if ("sd" %in% names(out_m)) {
  cat("\nParameter SDs:\n")
  for (param in key_params) {
    if (param %in% names(out_m$sd)) {
      cat(sprintf("  %-12s = %8.4f\n", param, out_m$sd[[param]]))
    }
  }
}

# Build clean p_unrep summary
p_unrep_means <- out_m$mean$p_unrep
p_unrep_sds   <- out_m$sd$p_unrep

p_unrep_final <- data.frame(
  arena        = site.order,
  p_unrep_mean = out_m$mean$p_unrep,
  p_unrep_sd   = out_m$sd$p_unrep,
  p_unrep_2.5  = out_m$q2.5$p_unrep,
  p_unrep_97.5 = out_m$q97.5$p_unrep
) %>%
  mutate(
    informed = case_when(
      arena %in% site.order.m1 ~ "Informed",
      TRUE                     ~ "Less informed"
    )
  )

identical(p_unrep_final$p_unrep_mean, out_m$mean$p_unrep)


# Check convergence across all N nodes
n_rhats <- out_m$summary[grep("^N\\[", rownames(out_m$summary)), "Rhat"]
cat("\nN node convergence:\n")
cat("Max Rhat:   ", round(max(n_rhats), 4), "\n")
cat("Mean Rhat:  ", round(mean(n_rhats), 4), "\n")
cat("N Rhat > 1.1:", sum(n_rhats > 1.1), "\n")

# Save outputs for Chapter 3
p_unrep_ch3 <- p_unrep_final
lambda_cols  <- grep("^lambda", rownames(out_m$summary), value = TRUE)
lambda_ch3   <- data.frame(
  param        = lambda_cols,
  arena        = site.order[as.integer(sub("lambda\\[(\\d+),.*", "\\1", lambda_cols))],
  year         = as.integer(sub("lambda\\[\\d+,(\\d+)\\]", "\\1", lambda_cols)),
  lambda_mean  = round(out_m$summary[lambda_cols, "mean"], 4),
  lambda_sd    = round(out_m$summary[lambda_cols, "sd"], 4),
  lambda_2.5   = round(out_m$summary[lambda_cols, "2.5%"], 4),
  lambda_97.5  = round(out_m$summary[lambda_cols, "97.5%"], 4)
)

#saveRDS(p_unrep_ch3, "priors/p_unrep_ch3.rds") #verify they save on desktop
#saveRDS(lambda_ch3,  "priors/lambda_ch3.rds")

```
```{r key outputs }

library(jagsUI)
saveRDS(out_m, "model2_full_results.rds")

# full convergence summary
check_neff(out_m, 200)
check_Rhat(out_m)

# traceplots for key parameters
traceplot(out_m, parameters = c("beta7", "beta8",  
                                 "intercept", "phi"))

```

Plots
```{r posterior lambda plots}
library(bayesplot)
library(ggplot2)
library(dplyr)

posterior <- as.matrix(out_m$samples)

# Figure 1 -- ecological drivers of growth
eco_params <- c("beta1", "beta3")

eco_plot <- mcmc_intervals(posterior, pars = eco_params) +
  scale_y_discrete(labels = c(
    "beta1" = "Drought Severity",
    "beta3" = "Flooded Forest Cover"
  )) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "red") +
  labs(
    title    = "Ecological drivers of population growth",
    subtitle = "50% and 95% credible intervals",
    x        = "Effect on annual growth rate (log scale)"
  ) +
  theme_minimal()

# Figure 2 -- social drivers of unreported fishing
social_params <- c("beta7", "beta8")

social_plot <- mcmc_intervals(posterior, pars = social_params) +
  scale_y_discrete(labels = c(
    "beta7" = "Poaching Frequency",
    "beta8" = "Non-compliance"
  )) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "red") +
  labs(
    title    = "Social drivers of unreported fishing",
    subtitle = "50% and 95% credible intervals",
    x        = "Effect on probability of unreported fishing (logit scale)"
  ) +
  theme_minimal()

# Figure 3 -- arena-level p_unrep
fa_lookup <- data.frame(
  site    = c("BC", "CA", "CO", "CR", "CS", "CV", "JA", "JC", "JF",
              "JG", "MI", "MU", "NP", "PP", "PV", "SE", "SJ", "SS", "VE"),
  fa      = c("AP", "CA", "CO", "AP", "AP", "CV", "JA", "JC", "FB",
              "JG", "AP", "AP", "FB", "FB", "PV", "SE", "SJ", "FB", "AP"),
  fa_full = c("Auati-Parana", "Caruara", "Coraci", "Auati-Parana", 
              "Auati-Parana", "Capivara", "Jaraua", "Jutai-Cleto", 
              "Fonte Boa", "Jurupari", "Auati-Parana", "Auati-Parana",
              "Fonte Boa", "Fonte Boa", "Parana Velho", "Seringa",
              "Sao Jose", "Fonte Boa", "Auati-Parana")
)

library(RColorBrewer)


p_unrep_plot_df <- data.frame(
  site    = site.order,
  mean    = out_m$mean$p_unrep,
  lower   = out_m$q2.5$p_unrep,
  upper   = out_m$q97.5$p_unrep,
  lower50 = out_m$q25$p_unrep,
  upper50 = out_m$q75$p_unrep
) %>%
  left_join(fa_lookup, by = "site") %>%
  arrange(mean) %>%
  mutate(site = factor(site, levels = site)) %>%
  mutate(
    informed = case_when(
      site %in% site.order.m1 ~ "Informed",
      TRUE                    ~ "Less informed"
    )
  )

n_fa <- length(unique(p_unrep_plot_df$fa_full))
my_colors <- colorRampPalette(brewer.pal(8, "Set2"))(n_fa)
fa_levels <- unique(p_unrep_plot_df$fa_full)
available_shapes <- c(16, 17, 15, 18, 8, 10, 7, 11, 12, 13, 14)
fa_shapes <- setNames(available_shapes[1:length(fa_levels)], fa_levels)


p_unrep_plot <- ggplot(p_unrep_plot_df,
                       aes(x = mean, y = site, color = fa_full, shape= fa_full)) +
  geom_point(size = 3) +
  geom_errorbarh(aes(xmin = lower, xmax = upper),
                 height = 0, linewidth = 0.5) +
  geom_errorbarh(aes(xmin = lower50, xmax = upper50),
                 height = 0, linewidth = 1.5) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "grey50") +
  scale_x_continuous(limits = c(0, 1),
                     labels = scales::percent_format()) +
  scale_color_manual(values = my_colors,
                     name = "Fishing Agreement")+
  scale_shape_manual(values = fa_shapes,
                     name   = "Fishing Agreement") +
  labs(
    title    = "Estimated unreported fishing by arena",
    subtitle = "Posterior mean with 50% and 95% credible intervals",
    x        = "Probability of unreported fishing",
    y        = NULL
  ) +
  theme_minimal() +
  theme(legend.position = "right")

# print all three
eco_plot
social_plot
p_unrep_plot
```
```{r p_unrep by arena}
library(ggplot2)
library(ggrepel)
ratio_df <- data.frame(
  arena      = site.order,
  mean_ratio = sapply(1:arenas, function(j) {
    ratios <- E[j, 2:years] / pmax(C[j, 1:(years-1)], 1)
    ratios[is.infinite(ratios)] <- NA
    mean(ratios, na.rm = TRUE)
  })
)

validation_df <- p_unrep_final %>%
  left_join(ratio_df, by = "arena")

cat("\nValidation df columns:", names(validation_df), "\n")
cat("\nSpearman correlation p_unrep vs harvest/count ratio:\n")
cat(round(cor(validation_df$p_unrep_mean,
              validation_df$mean_ratio,
              method = "spearman",
              use    = "complete.obs"), 3), "\n")


# informed vs uninformed p_unrep estimates
ggplot(validation_df, aes(x     = mean_ratio,
                           y     = p_unrep_mean,
                           color = informed,
                           label = arena)) +
  geom_point(aes(size = 1/p_unrep_sd)) +
  geom_errorbar(aes(ymin = p_unrep_2.5, ymax = p_unrep_97.5),
                width = 0.02, alpha = 0.5) +
  geom_text_repel(size = 3) +
  geom_vline(xintercept = 1, linetype = "dashed", color = "red") +
 scale_color_manual(
    values = c("Informed" = "steelblue", "Less informed" = "orange"),
    name   = "Prior type"
  ) +
  labs(x     = "Mean harvest / prior year count",
       y     = "Estimated p_unrep",
       color = "Prior type",
       size  = "Certainty",
       title = "Model validation: p_unrep vs independent harvest pressure index") +
  theme_minimal()

ggplot(p_unrep_final, aes(x = reorder(arena, p_unrep_mean), 
                           y = p_unrep_mean,
                           color = informed)) +
  geom_point(size = 3) +
  geom_errorbar(aes(ymin = p_unrep_2.5, ymax = p_unrep_97.5), 
                width = 0.3) +
  geom_hline(yintercept = mean(p_unrep_final$p_unrep_mean), 
             linetype = "dashed", color = "gray50") +
   scale_color_manual(
    values = c("Informed" = "steelblue", "Less informed" = "orange"),
    name   = "Prior type"
  ) +
  coord_flip() +
  labs(x     = "SES Arena",
       y     = "Estimated p_unrep",
       color = "Prior type",
       title = "Estimated unreported fishing rate by arena",
       subtitle = "Points = posterior median, bars = 95% credible interval\nDashed line = system-wide mean") +
  theme_minimal()
```
```{r perceptions data comparison}
library(tidyr)
library(ggplot2)
library(ggrepel)
library(dplyr)

# Perceptions data only - independent from model inputs
# (IQ and poaching were used in the model, perceptions were not)
predictors <- c("perc_size", "perc_sea", "perc_lake")
labels     <- c("Perception: Size limits", 
                "Perception: Seasonal limits",
                "Perception: Lake restrictions")

social_compare <- p_unrep_final %>%
  left_join(
    data.frame(
      arena     = per_comp2$SES.name,
      perc_size = per_comp2$compmgts,
      perc_sea  = per_comp2$compmgtsea,
      perc_lake = per_comp2$compmgtla
    ),
    by = "arena"
  )

# Spearman correlations
run_correlations <- function(df, p_unrep_col, predictors, labels) {
  results <- data.frame(predictor = labels, r = NA, p = NA, n = NA)
  for(i in seq_along(predictors)) {
    x    <- df[[predictors[i]]]
    y    <- df[[p_unrep_col]]
    keep <- !is.na(x) & !is.na(y)
    ct   <- cor.test(x[keep], y[keep], method = "spearman")
    results$r[i] <- round(ct$estimate, 3)
    results$p[i] <- round(ct$p.value, 3)
    results$n[i] <- sum(keep)
  }
  return(results)
}

corr_results <- run_correlations(social_compare, "p_unrep_mean", 
                                  predictors, labels)
print(corr_results)

# R2 labels for facets
social_long <- social_compare %>%
  pivot_longer(
    cols      = all_of(predictors),
    names_to  = "predictor",
    values_to = "score"
  ) %>%
  mutate(
    predictor_label = recode(predictor,
      perc_size = "Perception: Size limits",
      perc_sea  = "Perception: Seasonal limits",
      perc_lake = "Perception: Lake restrictions"
    )
  )

r2_df <- social_long %>%
  filter(!is.na(score) & !is.na(p_unrep_mean)) %>%
  group_by(predictor_label) %>%
  summarise(
    r2   = round(summary(lm(p_unrep_mean ~ score))$r.squared, 3),
    pval = round(summary(lm(p_unrep_mean ~ score))$coefficients[2, 4], 3),
    .groups = "drop"
  ) %>%
  mutate(
    label        = paste0("R² = ", r2, ", p = ", pval),
    score        = -Inf,
    p_unrep_mean = Inf
  )

# Plot
ggplot(social_long,
       aes(x = score, y = p_unrep_mean,
           color = informed, label = arena)) +
  geom_point(size = 2) +
  geom_errorbar(aes(ymin = p_unrep_2.5, ymax = p_unrep_97.5),
                width = 0.02, alpha = 0.4) +
  geom_smooth(method = "lm", se = TRUE,
              color = "gray30", linetype = "dashed") +
  geom_text_repel(size = 2.5) +
  geom_text(data = r2_df,
            aes(x = score, y = p_unrep_mean, label = label),
            hjust = -0.05, vjust = 1.5,
            color = "gray20", size = 3,
            inherit.aes = FALSE) +
  scale_color_manual(
    values = c("Informed" = "steelblue", "Less informed" = "orange"),
    name   = "Prior type"
  ) +
  facet_wrap(~predictor_label, scales = "free_x", ncol = 3) +
  labs(
    x        = "Community perception of non-compliance",
    y        = "Estimated unreported fishing (p_unrep)",
    title    = "Estimated unreported fishing vs independent non-compliance perceptions",
    subtitle = "Points = posterior mean, bars = 95% CI | Perceptions data not used in model"
  ) +
  theme_minimal() +
  theme(strip.text = element_text(face = "bold"))
```
Ecological model (truncated)
```{r eco mod last5}
library(rjags)
library(jagsUI)

data.bundle_eco <- list(
  C            = C,
  E            = E,
  w_fixed      = W,
  Minw         = Wl_min_scaled,
  Ff           = ff_scaled,
  arenas       = arenas,
  years        = years,
  station_id   = station_id,
  N_start      = data.bundle_m$N_start,
  r_prior_mean = r_prior_m2$r_mean,
  r_prior_sd   = r_prior_m2$r_sd,
  beta1_prior  = beta_priors$beta1_mean,
  beta1_prior_sd = beta_priors$beta1_sd * 2,
  beta3_prior  = beta_priors$beta3_mean,
  beta3_prior_sd = beta_priors$beta3_sd * 2
)

modfile_eco <- "model_eco_last5.txt"
writeLines("
model {
  beta1 ~ dnorm(beta1_prior, 1/pow(beta1_prior_sd, 2))
  beta3 ~ dnorm(beta3_prior, 1/pow(beta3_prior_sd, 2))
  #beta6 ~ dnorm(beta6_prior, 1/pow(beta6_prior_sd, 2))T(0,)

  for (j in 1:arenas) {
    N[j,1] ~ dpois(N_start[j])
    r[j] ~ dnorm(r_prior_mean[j], 1/pow(r_prior_sd[j], 2))T(-0.5, 0.5)

    for (t in 1:(years-1)){
      N_post_harvest[j,t] <- N[j,t] - E[j,t]
      growth_rate[j,t]    <- r[j] +
                             (beta1 * Minw[station_id[j],t]) +
                             (beta3 *Ff[j,t])
      N_expected[j,t+1]   <- N_post_harvest[j,t] * exp(growth_rate[j,t])
      N[j,t+1]            ~ dpois(N_expected[j,t+1])
    }
  }

  for (j in 1:arenas){
    for (t in 1:years){
      
      M[j,t]   ~ dbin(w_fixed[j,t], N[j,t])
    }
  }

  p_obs <- 0.85

  for (j in 1:arenas) {
    for (t in 1:years){
      C[j,t] ~ dbin(p_obs, M[j,t])
    }
  }

  for (j in 1:arenas) {
    for (t in 1:(years-1)) {
      lambda[j,t+1] <- N[j,t+1]/N[j,t]
    }
  }
}
", con = modfile_eco)

inits_eco <- function() {
  list(
    N     = N_sim,
    M     = M_sim,
    r     = rnorm(arenas, r_prior_m2$r_mean, 0.01),
    beta1 = rnorm(1, beta_priors$beta1_mean, 0.001),
    beta3 = rnorm(1, beta_priors$beta3_mean, 0.001)
  )
}

parameters_eco <- c("beta1", "beta3", "lambda", "N", "r")

out_eco <- jags(data = data.bundle_eco,
                inits = inits_eco,
                parameters.to.save = parameters_eco,
                model.file = modfile_eco,
                n.chains = 3,
                n.adapt = 30000,
                n.iter = 200000,
                n.burnin = 100000,
                n.thin = 75,
                parallel = TRUE) 
```
```{r model comparison}
# Compare lambda estimates between models
N_eco_mean  <- apply(out_eco$sims.list$N, c(2,3), mean)
N_full_mean <- apply(out_m$sims.list$N,   c(2,3), mean)

# Lambda from each model
lambda_eco  <- N_eco_mean[,  2:5] / N_eco_mean[,  1:4]
lambda_full <- N_full_mean[, 2:5] / N_full_mean[, 1:4]

rownames(lambda_eco)  <- site.order
rownames(lambda_full) <- site.order
colnames(lambda_eco)  <- colnames(lambda_full) <- as.character(2019:2022)

# Mean lambda by arena across years
lambda_compare <- data.frame(
  arena       = site.order,
  lambda_eco  = rowMeans(lambda_eco,  na.rm=TRUE),
  lambda_full = rowMeans(lambda_full, na.rm=TRUE)
) %>%
  mutate(
    diff     = lambda_full - lambda_eco,
    informed = ifelse(arena %in% site.order.m1, "Informed", "Less informed")
  ) %>%
  arrange(desc(abs(diff)))

print(lambda_compare)

# Is lambda systematically different between models?
cat("\nMean lambda - eco:", round(mean(lambda_eco), 3), "\n")
cat("Mean lambda - full:", round(mean(lambda_full), 3), "\n")
cat("Mean difference:", round(mean(lambda_compare$diff), 3), "\n")

# Plot lambda comparison by arena
lambda_compare_long <- lambda_compare %>%
  pivot_longer(
    cols      = c(lambda_eco, lambda_full),
    names_to  = "model",
    values_to = "lambda"
  ) %>%
  mutate(
    model = recode(model,
      lambda_eco  = "Ecological only",
      lambda_full = "Full model"
    )
  )

ggplot(lambda_compare_long, 
       aes(x = reorder(arena, lambda), y = lambda, 
           color = model, shape = informed)) +
  geom_point(size = 3) +
  geom_line(aes(group = arena), color = "gray70", linewidth = 0.5) +
  geom_hline(yintercept = 1, linetype = "dashed", color = "red") +
  scale_color_manual(
    values = c("Ecological only" = "coral",
               "Full model"      = "steelblue"),
    name = "Model"
  ) +
  scale_shape_manual(
    values = c("Informed" = 16, "Less informed" = 17),
    name = "Prior type"
  ) +
  coord_flip() +
  labs(
    x        = "SES Arena",
    y        = "Mean annual population growth rate (lambda)",
    title    = "Effect of accounting for unreported fishing on lambda",
    subtitle = "Lines connect same arena across models | Red dashed = stable population"
  ) +
  theme_minimal()
```
```{r population trends}
year_lookup <- setNames(2019:2022, 2:5)
extract_lambda <- function(out, model_name, site_order){
  lambda_mean   <- out$mean$lambda
  lambda_low    <- out$q2.5$lambda
  lambda_high   <- out$q97.5$lambda
  lambda_low50  <- out$q25$lambda
  lambda_high50 <- out$q75$lambda
  df <- expand.grid(j = 1:length(site_order), t = 2:5) %>%
    mutate(
      site    = site_order[j],
      year    = year_lookup[as.character(t)],
      mean    = mapply(function(j,t) lambda_mean[j,t],   j, t),
      lower   = mapply(function(j,t) lambda_low[j,t],    j, t),
      upper   = mapply(function(j,t) lambda_high[j,t],   j, t),
      lower50 = mapply(function(j,t) lambda_low50[j,t],  j, t),
      upper50 = mapply(function(j,t) lambda_high50[j,t], j, t),
      model   = model_name
    ) %>%
    select(-j, -t)
  return(df)
}
lambda_mort <- extract_lambda(out_m,   "Full model",       site.order)
lambda_eco  <- extract_lambda(out_eco, "Ecological only",  site.order)

lambda_both <- rbind(lambda_mort, lambda_eco) %>%
  left_join(fa_lookup[, c("site", "fa_full")], by = "site")

# plot
ggplot(lambda_both, aes(x = year, y = mean, color = model, fill = model)) +
  geom_hline(yintercept = 1, linetype = "dashed", color = "gray50") +
  geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0.15, color = NA) +
  geom_ribbon(aes(ymin = lower50, ymax = upper50), alpha = 0.30, color = NA) +
  geom_line() +
  geom_point(size = 1.5) +
  scale_color_manual(values = c("Full model" = "steelblue", 
                                "Ecological only" = "coral"),
                     name = "Model") +
  scale_fill_manual(values  = c("Full model" = "steelblue",
                                "Ecological only" = "coral"),
                    name = "Model") +
  scale_x_continuous(breaks = 2019:2022) +
  facet_wrap(~site, ncol = 5) +
  labs(
    x        = "Year",
    y        = "Population growth rate (lambda)",
    title    = "Annual population growth rate by arena",
    subtitle = "50% and 95% credible intervals | Dashed line = stable population (lambda = 1)"
  ) +
  theme_minimal() +
  theme(
    strip.text       = element_text(face = "bold"),
    axis.text.x      = element_text(angle = 45, hjust = 1),
    legend.position  = "bottom"
  )
```
```{r U vs E}
library(tidyr)
library(dplyr)
library(ggplot2)
library(viridis)

# Extract posterior mean and CI for U
U_mean  <- apply(out_m$sims.list$U, c(2,3), mean)
U_lower <- apply(out_m$sims.list$U, c(2,3), quantile, 0.025)
U_upper <- apply(out_m$sims.list$U, c(2,3), quantile, 0.975)

rownames(U_mean) <- rownames(U_lower) <- rownames(U_upper) <- site.order
colnames(U_mean) <- colnames(U_lower) <- colnames(U_upper) <- as.character(2018:2021)
n_sims <- dim(out_m$sims.list$p_unrep)[1]
U_2022_sims <- matrix(NA, nrow = n_sims, ncol = arenas)

for(j in 1:arenas) {
  N_2022    <- out_m$sims.list$N[, j, 5]      # posterior N for year 5 (2022)
  E_2022    <- E[j, 5]                          # observed harvest 2022
  p_unrep_j <- out_m$sims.list$p_unrep[, j]   # posterior p_unrep
  avail     <- pmax(round(N_2022) - E_2022, 0) # available fish
  U_2022_sims[, j] <- rbinom(n_sims, avail, p_unrep_j)
}

# Summarize
U_2022_mean  <- apply(U_2022_sims, 2, mean)
U_2022_lower <- apply(U_2022_sims, 2, quantile, 0.025)
U_2022_upper <- apply(U_2022_sims, 2, quantile, 0.975)

# ============================================================
# Extend existing U arrays to include 2022
# ============================================================

# Current U arrays are [arenas x 4] (2018-2021)
# Add 2022 as a 5th column
U_mean_full  <- cbind(U_mean,  U_2022_mean)
U_lower_full <- cbind(U_lower, U_2022_lower)
U_upper_full <- cbind(U_upper, U_2022_upper)

colnames(U_mean_full) <- colnames(U_lower_full) <- 
  colnames(U_upper_full) <- as.character(2018:2022)

rownames(U_mean_full) <- rownames(U_lower_full) <- 
  rownames(U_upper_full) <- site.order

# Verify
cat("U_mean_full dimensions:", dim(U_mean_full), "\n")  # should be 19 x 5
round(U_mean_full["JA", ])  # check JA looks reasonable

# ============================================================
# Rebuild harvest_long with full 2018:2022 E and U
# ============================================================

# E for all 5 years
E_sub <- E[, 1:5]
colnames(E_sub) <- as.character(2018:2022)

harvest_long <- bind_rows(
  # Reported harvest
  as.data.frame(E_sub) %>%
    mutate(arena = site.order) %>%
    pivot_longer(-arena, names_to = "year", values_to = "value") %>%
    mutate(type = "Reported (E)", lower = value, upper = value),
  
  # Unreported harvest
  as.data.frame(U_mean_full) %>%
    mutate(arena = site.order) %>%
    pivot_longer(-arena, names_to = "year", values_to = "value") %>%
    left_join(
      as.data.frame(U_lower_full) %>%
        mutate(arena = site.order) %>%
        pivot_longer(-arena, names_to = "year", values_to = "lower"),
      by = c("arena", "year")
    ) %>%
    left_join(
      as.data.frame(U_upper_full) %>%
        mutate(arena = site.order) %>%
        pivot_longer(-arena, names_to = "year", values_to = "upper"),
      by = c("arena", "year")
    ) %>%
    mutate(type = "Unreported (U)")
) %>%
  mutate(
    year     = as.integer(year),
    arena    = factor(arena, levels = site.order),
    informed = ifelse(arena %in% site.order.m1, "Informed", "Less informed")
  )
harvest_long <- harvest_long %>%
  mutate(
    x_pos = as.numeric(factor(year)) + 
             ifelse(type == "Reported (E)", -0.18, 0.18)
  )

u_only <- harvest_long %>% 
  filter(type == "Unreported (U)")

ggplot(harvest_long, aes(x = x_pos, y = value, fill = type)) +
  geom_bar(stat = "identity", width = 0.35) +
  geom_errorbar(
    data = u_only,
    aes(x = x_pos, ymin = lower, ymax = upper),
    inherit.aes = FALSE,
    width = 0.15, 
    color = "gray20", 
    linewidth = 0.5
  ) +
  scale_x_continuous(
    breaks = 1:5,
    labels = as.character(2018:2022)
  ) +
  scale_fill_manual(
    values = c("Reported (E)"   = "steelblue",
               "Unreported (U)" = "coral"),
    name = "Harvest type"
  ) +
  facet_wrap(~arena, ncol = 5, scales = "free_y") +
  labs(
    x        = "Year",
    y        = "Number of fish",
    title    = "Reported vs estimated unreported harvest by arena",
    subtitle = "Error bars show 95% CI on unreported harvest estimate"
  ) +
  theme_minimal() +
  theme(
    strip.text      = element_text(face = "bold"),
    axis.text.x     = element_text(angle = 45, hjust = 1),
    legend.position = "bottom"
  )

# ============================================================
# Plot 2 - Ratio of unreported to total harvest
# ============================================================
ratio_long <- data.frame(
  arena  = rep(site.order, 5),
  year   = rep(2018:2022, each = arenas),
  E      = as.vector(E_sub),
  U_mean = as.vector(U_mean_full),   # changed from U_mean
  U_low  = as.vector(U_lower_full),  # changed from U_lower
  U_high = as.vector(U_upper_full)   # changed from U_upper
) %>%
  mutate(
    total      = E + U_mean,
    ratio_mean = ifelse(total > 0, U_mean / total, NA),
    ratio_low  = ifelse(total > 0, U_low  / (E + U_low),  NA),
    ratio_high = ifelse(total > 0, U_high / (E + U_high), NA),
    arena      = factor(arena, levels = site.order),
    informed   = ifelse(arena %in% site.order.m1, "Informed", "Less informed")
  )


ggplot(ratio_long, aes(x = year, y = ratio_mean, 
                        color = arena, fill = arena)) +
  geom_ribbon(aes(ymin = ratio_low, ymax = ratio_high), 
              alpha = 0.2, color = NA) +
  geom_line(linewidth = 0.8) +
  geom_point(size = 2) +
  geom_hline(yintercept = 0.5, linetype = "dashed", 
             color = "red", linewidth = 0.5) +
  scale_color_viridis_d() +
  scale_fill_viridis_d() +
  scale_y_continuous(labels = scales::percent_format(),
                     limits = c(0, 1)) +
  scale_x_continuous(breaks = 2018:2022) +
  facet_wrap(~arena, ncol = 5) +
  labs(
    x        = "Year",
    y        = "Unreported harvest as % of total harvest",
    title    = "Proportion of total harvest that is unreported",
    subtitle = "Red dashed = 50% unreported | Ribbons show 95% CI"
  ) +
  theme_minimal() +
  theme(
    strip.text      = element_text(face = "bold"),
    axis.text.x     = element_text(angle = 45, hjust = 1),
    legend.position = "none"
  )
```